-- BUDI Seed Data
-- This file contains development seed data.
-- WARNING: Do not use in production.

-- Seed schools
INSERT INTO schools (id, name, slug, address, phone, email)
VALUES
  ('00000000-0000-0000-0000-000000000001', 'SMA Negeri 1 Jakarta', 'sman1-jkt', 'Jl. Merdeka No. 1, Jakarta', '021-12345678', 'info@sman1-jkt.sch.id'),
  ('00000000-0000-0000-0000-000000000002', 'SMP Bina Bangsa', 'smp-bbangsa', 'Jl. Pendidikan No. 10, Bandung', '022-87654321', 'info@smp-bbinabangsa.sch.id')
ON CONFLICT (id) DO NOTHING;

-- Note: Add seed data for other tables as they are created
-- See docs/database.md for table definitions

-- ============================================================
-- DEVELOPMENT SEED: AUTHENTICATED TEST USERS
-- WARNING: These are strictly for LOCAL DEVELOPMENT ONLY.
-- Do not ever execute this block in production.
-- ============================================================
DO $$
DECLARE
    superadmin_uid UUID := '00000000-0000-0000-0000-000000000010';
    admin_uid UUID := '00000000-0000-0000-0000-000000000011';
    teacher_uid UUID := '00000000-0000-0000-0000-000000000012';
    staff_uid UUID := '00000000-0000-0000-0000-000000000013';
    
    v_school_id UUID := '00000000-0000-0000-0000-000000000001';
    
    superadmin_role_id UUID;
    admin_role_id UUID;
    teacher_role_id UUID;
    staff_role_id UUID;
    
    dev_password_hash TEXT;
BEGIN
    -- Use the Supabase-provided pgcrypto extension from the extensions schema
    dev_password_hash := extensions.crypt('BudiLocal123!', extensions.gen_salt('bf'));

    -- 1. Insert into auth.users
    -- The profiles will be auto-generated by the handle_new_user trigger in 001_core_tables.sql
    INSERT INTO auth.users (
        id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, 
        raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
        confirmation_token, recovery_token, email_change_token_new, email_change
    )
    VALUES 
        (superadmin_uid, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'superadmin@budi.local', dev_password_hash, now(), '{"provider": "email", "providers": ["email"]}', '{"full_name": "Super Admin"}', now(), now(), '', '', '', ''),
        (admin_uid, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'admin@budi.local', dev_password_hash, now(), '{"provider": "email", "providers": ["email"]}', '{"full_name": "School Admin"}', now(), now(), '', '', '', ''),
        (teacher_uid, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'teacher@budi.local', dev_password_hash, now(), '{"provider": "email", "providers": ["email"]}', '{"full_name": "Teacher"}', now(), now(), '', '', '', ''),
        (staff_uid, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'staff@budi.local', dev_password_hash, now(), '{"provider": "email", "providers": ["email"]}', '{"full_name": "Staff"}', now(), now(), '', '', '', '')
    ON CONFLICT (id) DO UPDATE SET encrypted_password = EXCLUDED.encrypted_password;

    -- Insert into auth.identities to ensure email login works
    INSERT INTO auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
    VALUES
        (superadmin_uid, superadmin_uid, format('{"sub":"%s","email":"%s"}', superadmin_uid::text, 'superadmin@budi.local')::jsonb, 'email', superadmin_uid::text, now(), now(), now()),
        (admin_uid, admin_uid, format('{"sub":"%s","email":"%s"}', admin_uid::text, 'admin@budi.local')::jsonb, 'email', admin_uid::text, now(), now(), now()),
        (teacher_uid, teacher_uid, format('{"sub":"%s","email":"%s"}', teacher_uid::text, 'teacher@budi.local')::jsonb, 'email', teacher_uid::text, now(), now(), now()),
        (staff_uid, staff_uid, format('{"sub":"%s","email":"%s"}', staff_uid::text, 'staff@budi.local')::jsonb, 'email', staff_uid::text, now(), now(), now())
    ON CONFLICT (provider, provider_id) DO NOTHING;

    -- Get Role IDs
    SELECT id INTO superadmin_role_id FROM public.roles WHERE code = 'super_admin';
    SELECT id INTO admin_role_id FROM public.roles WHERE code = 'school_admin';
    SELECT id INTO teacher_role_id FROM public.roles WHERE code = 'teacher';
    SELECT id INTO staff_role_id FROM public.roles WHERE code = 'staff';

    -- 2. Assign Global Role (Super Admin only usually)
    INSERT INTO public.user_roles (user_id, role_id)
    VALUES 
        (superadmin_uid, superadmin_role_id)
    ON CONFLICT (user_id, role_id) DO NOTHING;

    -- 3. Assign School Users (link to school 1)
    INSERT INTO public.school_users (school_id, user_id, role_id, is_default)
    VALUES
        (v_school_id, superadmin_uid, superadmin_role_id, true),
        (v_school_id, admin_uid, admin_role_id, true),
        (v_school_id, teacher_uid, teacher_role_id, true),
        (v_school_id, staff_uid, staff_role_id, true)
    ON CONFLICT (school_id, user_id) DO NOTHING;
END;
$$;
