/**
 * BUDI Engineering Review Workflow
 * Generates a comprehensive review report for CI/CD and code review.
 * Cross-platform (Windows, Linux, Mac).
 *
 * Usage: node scripts/review/build-review.js
 * Output: reports/latest/SUMMARY.md
 */

import { execSync } from 'child_process';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
const REPORTS_DIR = resolve(ROOT, 'reports/latest');
const TIMESTAMP = new Date().toISOString();

function ensureDir(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function run(cmd, label) {
  try {
    const out = execSync(cmd, { cwd: ROOT, encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024 });
    return { stdout: out.trim(), stderr: '', exitCode: 0 };
  } catch (e) {
    return {
      stdout: e.stdout?.trim() || '',
      stderr: e.stderr?.trim() || e.message,
      exitCode: e.status ?? 1,
    };
  }
}

function runQuiet(cmd) {
  try {
    return execSync(cmd, { cwd: ROOT, encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024 }).trim();
  } catch {
    return '(error running command)';
  }
}

// ---- Collect Data ----

console.log('🔍 BUDI Engineering Review\n');

// 1. Git status
console.log('  • Git status...');
const gitStatus = run('git status --short');
writeFileSync(
  resolve(REPORTS_DIR, 'changed-files.txt'),
  gitStatus.stdout || '(clean working tree)',
);

// 2. Git diff against HEAD~1
console.log('  • Git diff...');
const gitDiff = run('git diff HEAD~1 --stat');
const gitDiffFull = run('git diff HEAD~1');
writeFileSync(resolve(REPORTS_DIR, 'git.diff'), gitDiffFull.stdout || gitDiffFull.stderr);

// 3. Last 5 commits
console.log('  • Git log...');
const gitLog = run('git log --oneline -5');
writeFileSync(resolve(REPORTS_DIR, 'commits.txt'), gitLog.stdout || '(no commits)');

// 4. Lint results
console.log('  • ESLint...');
const lintResult = run('pnpm lint --no-cache 2>&1');
const lintOut = lintResult.stdout + (lintResult.stderr ? '\n\nSTDERR:\n' + lintResult.stderr : '');
writeFileSync(resolve(REPORTS_DIR, 'lint.txt'), lintOut || '(no lint output)');

// 5. TypeScript type checking
console.log('  • TypeScript...');
const typecheckResult = run('pnpm typecheck 2>&1');
writeFileSync(
  resolve(REPORTS_DIR, 'typecheck.txt'),
  typecheckResult.stdout + (typecheckResult.stderr ? '\n\nSTDERR:\n' + typecheckResult.stderr : ''),
);

// 6. Build
console.log('  • Build...');
const buildResult = run('pnpm build 2>&1');
writeFileSync(
  resolve(REPORTS_DIR, 'build.txt'),
  buildResult.stdout + (buildResult.stderr ? '\n\nSTDERR:\n' + buildResult.stderr : ''),
);

// ---- Generate SUMMARY.md ----
console.log('  • Generating summary...\n');

const commitCount = gitLog.stdout ? gitLog.stdout.split('\n').length : 0;
const changedCount = gitStatus.stdout ? gitStatus.stdout.split('\n').length : 0;
const lintExit = lintResult.exitCode;
const typeExit = typecheckResult.exitCode;
const buildExit = buildResult.exitCode;

const summary = `# BUDI Engineering Review Report

**Generated:** ${TIMESTAMP}
**Status:** ${lintExit === 0 && typeExit === 0 && buildExit === 0 ? '✅ ALL CHECKS PASSED' : '❌ CHECKS FAILED'}

---

## Summary

| Check | Status |
|-------|--------|
| Lint | ${lintExit === 0 ? '✅ Pass' : '❌ Fail'} |
| TypeScript | ${typeExit === 0 ? '✅ Pass' : '❌ Fail'} |
| Build | ${buildExit === 0 ? '✅ Pass' : '❌ Fail'} |
| Changed Files | ${changedCount} files |
| Recent Commits | ${commitCount} commits |

## File Overview

\`\`\`
${gitDiff.stdout || '(no changes)'}
\`\`\`

## Changed Files

\`\`\`
${gitStatus.stdout || '(clean working tree)'}
\`\`\`

## Recent Commits

\`\`\`
${gitLog.stdout || '(no commits)'}
\`\`\`

## Detailed Reports

| Report | File |
|--------|------|
| Lint Report | [lint.txt](lint.txt) |
| TypeScript Report | [typecheck.txt](typecheck.txt) |
| Build Report | [build.txt](build.txt) |
| Git Diff | [git.diff](git.diff) |
| Changed Files | [changed-files.txt](changed-files.txt) |
| Commits | [commits.txt](commits.txt) |
| Project Status | [project-status.json](project-status.json) |

---

*Report auto-generated by BUDI Review Workflow*
`;

writeFileSync(resolve(REPORTS_DIR, 'SUMMARY.md'), summary);

// ---- Generate project-status.json ----
const statusJson = {
  generatedAt: TIMESTAMP,
  status: lintExit === 0 && typeExit === 0 && buildExit === 0 ? 'pass' : 'fail',
  checks: {
    lint: { exitCode: lintExit, passed: lintExit === 0 },
    typecheck: { exitCode: typeExit, passed: typeExit === 0 },
    build: { exitCode: buildExit, passed: buildExit === 0 },
  },
  files: {
    changed: changedCount,
    committed: commitCount,
  },
  reports: {
    lint: 'lint.txt',
    typecheck: 'typecheck.txt',
    build: 'build.txt',
    gitDiff: 'git.diff',
    changedFiles: 'changed-files.txt',
    commits: 'commits.txt',
  },
};

writeFileSync(resolve(REPORTS_DIR, 'project-status.json'), JSON.stringify(statusJson, null, 2));

console.log('✅ Review report generated at: reports/latest/');
console.log(
  `   Lint: ${lintExit === 0 ? '✅' : '❌'} | TypeScript: ${typeExit === 0 ? '✅' : '❌'} | Build: ${buildExit === 0 ? '✅' : '❌'}`,
);
